minimum_pre_commit_version: 2.15.0

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.1.13'
    hooks:
      - id: ruff
        args:
          - --fix
      - id: ruff-format
        args:
          - --quiet
