sudo: false
language: python
env:
  - DEBUG=1
cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.npm"
python: 3.6
install:
- ". $HOME/.nvm/nvm.sh"
- nvm install stable
- nvm use stable
- npm install
- pip install -U pip
- pip install -r requirements.txt -r requirements-dev.txt
script:
- npm run build
- python manage.py setup
- python manage.py test
notifications:
  slack:
    secure: lfDX47584szMKqN0JharV3W7Hk8/xRruVbC+DGlSrq7qyH3txtoeL8qyT1fPydd9mZTDGWXvxj/1FlKK6Og0DUl0kjts/CXhBmA0USQouL/byp+Hm7PDPuvLBU0M77MhDCAzDgLCw3oxxVewLqaL8tQkY7tR1KLVtHBBq+72/rQ=
