version: '2'
services:
  web:
    build: .
    command: python manage.py docker_start
    ports:
      - 8000:8000
    links:
      - rabbitmq
      - postgres
      - memcache
    volumes:
      - .:/usr/src/app
    environment:
      DEBUG: 1
      DATABASE_URL: psql://kompassi:secret@postgres/kompassi
      BROKER_URL: amqp://guest:guest@rabbitmq/
      KOMPAQ_URL: amqp://guest:guest@rabbitmq/
      CACHE_URL: memcache://memcache
      ALLOWED_HOSTS: '*'
  celery:
    build: .
    command: celery -A kompassi.celery_app:app worker
    links:
      - rabbitmq
      - postgres
      - memcache
    volumes:
      - .:/usr/src/app:ro
    environment:
      DEBUG: 1
      DATABASE_URL: psql://kompassi:secret@postgres/kompassi
      BROKER_URL: amqp://guest:guest@rabbitmq/
      CACHE_URL: memcache://memcache
  postgres:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: kompassi
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: kompassi
  rabbitmq:
    image: rabbitmq
    ports:
      - 5672:5672
  memcache:
    image: memcached
volumes:
  postgres-data:
    driver: local
