version: '2'
services:
  web:
    image: tracon/kompassi
    build: .
    ports:
      - 8000:8000
    links:
      - rabbitmq
      - postgres
      - memcache
    environment:
      DEBUG: 1
      DATABASE_URL: psql://postgres/kompassi
      BROKER_URL: amqp://guest:guest@rabbitmq/
      CACHE_URL: memcache://memcache
  celery:
    image: tracon/kompassi

    links:
      - rabbitmq
      - postgres
      - memcache
    environment:
      DEBUG: 1
  postgres:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq
  memcache:
    image: memcached
volumes:
  postgres-data:
    driver: local
