version: '2.2'
services:
  web:
    build: .
    init: true
    command: python manage.py docker_start
    ports:
      - 8000:8000
    links:
      - redis
      - postgres
    volumes:
      - .:/usr/src/app
      - web-media:/usr/src/app/media
    environment: &environment
      PYTHONUNBUFFERED: 1
      DEBUG: 1
      DATABASE_URL: psql://kompassi:secret@postgres/kompassi
      BROKER_URL: redis://redis/1
      CACHE_URL: rediscache://redis/1
      ALLOWED_HOSTS: '*'
  celery:
    build: .
    init: true
    command: celery -A kompassi.celery_app:app worker
    links:
      - redis
      - postgres
    volumes:
      - .:/usr/src/app:ro
    environment:
      <<: *environment
  postgres:
    # image: postgres
    build: ./kompassi/sql/
    init: true
    volumes:
      - postgres-data:/var/lib/postgresql/data
      #- ./kompassi-202012011746.sql:/docker-entrypoint-initdb.d/00-schema.sql
    environment:
      POSTGRES_USER: kompassi
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: kompassi
  redis:
    image: redis
    init: true
    volumes:
      - redis-data:/data

volumes:
  postgres-data: {}
  redis-data: {}
  web-media: {}
