---
version: '2'
name: kompassi
services:
  web:
    extends:
      file: docker-compose.yml
      service: web
    image: registry.kontena.local/kompassi:latest
  celery:
    extends:
      file: docker-compose.yml
      service: celery
    image: registry.kontena.local/kompassi:latest
  postgres:
    extends:
      file: docker-compose.yml
      service: postgres
  rabbitmq:
    extends:
      file: docker-compose.yml
      service: rabbitmq
  memcache:
    extends:
      file: docker-compose.yml
      service: memcache
