---
version: '2'
name: kompassi
services:
  web:
    image: tracon/kompassi
    command: gunicorn --bind=0.0.0.0:8000 --workers=4 turska.wsgi:application
    links:
      - rabbitmq
      - postgres
      - memcache
    environment:
      DEBUG: 1
      DATABASE_URL: psql://kompassi:secret@kompassi-postgres.kontena.local/kompassi
      BROKER_URL: amqp://guest:guest@kompassi-rabbitmq.kontena.local/
      CACHE_URL: memcache://kompassi-memcache.kontena.local
      KONTENA_LB_MODE: http
      KONTENA_LB_BALANCE: roundrobin
      KONTENA_LB_INTERNAL_PORT: 8000
      KONTENA_LB_VIRTUAL_HOSTS: kompassi.dev
    external_links:
      - platform-external_lb
  celery:
    image: tracon/kompassi
    command: celery -A turska.celery_app:app worker
    links:
      - rabbitmq
      - postgres
      - memcache
    environment:
      DEBUG: 1
      DATABASE_URL: psql://kompassi:secret@kompassi-postgres.kontena.local/kompassi
      BROKER_URL: amqp://guest:guest@kompassi-rabbitmq.kontena.local/
      CACHE_URL: memcache://kompassi-memcache.kontena.local
  postgres:
    image: postgres
    stateful: true
    environment:
      POSTGRES_USER: kompassi
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: kompassi
  rabbitmq:
    image: rabbitmq
    stateful: true
  memcache:
    image: memcached
