apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery
spec:
  selector:
    matchLabels:
      stack: kompassi
      component: celery
  template:
    metadata:
      labels:
        stack: kompassi
        component: celery
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: component
                  operator: In
                  values:
                  - celery
              topologyKey: "kubernetes.io/hostname"
      enableServiceLinks: false
      securityContext: !Var kompassi_pod_security_context
      containers:
        - name: master
          image: !Var kompassi_image
          args: ["celery", "-A", "kompassi.celery_app:app", "worker", "-l", "DEBUG"]
          env: !Var kompassi_environment
          volumeMounts: !Var kompassi_volume_mounts
          securityContext: !Var kompassi_container_security_context
      volumes: !Var kompassi_volumes
