apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  selector:
    matchLabels:
      stack: kompassi
      component: rabbitmq
  template:
    metadata:
      labels:
        stack: kompassi
        component: rabbitmq
    spec:
      containers:
        - name: master
          image: !Var rabbitmq_image
          ports:
            - containerPort: 5672
          env:
            - name: RABBITMQ_DEFAULT_VHOST
              value: !Var rabbitmq_vhost
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: password
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: username
          volumeMounts:
            - !If
                test: !Any [!Var rabbitmq_storage_pvc, !Var rabbitmq_storage_cephfs]
                then:
                  mountPath: /var/lib/rabbitmq
                  name: rabbitmq-data
      volumes:
        - !If
            test: !Var rabbitmq_storage_pvc
            then:
              name: rabbitmq-data
              persistentVolumeClaim:
                claimName: rabbitmq-data
        - !If
            test: !Var rabbitmq_storage_cephfs
            then:
              name: rabbitmq-data
              flexVolume:
                driver: ceph.rook.io/rook
                fsType: ceph
                options:
                  fsName: !Var rabbitmq_storage_cephfs
                  clusterNamespace: !Var rabbitmq_storage_cephfs_namespace
                  path: !Var rabbitmq_storage_cephfs_path
