apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      stack: kompassi
      component: nginx
  template:
    metadata:
      labels:
        stack: kompassi
        component: nginx
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: component
                  operator: In
                  values:
                  - nginx
              topologyKey: "kubernetes.io/hostname"
      enableServiceLinks: false
      containers:
        - name: master
          image: !Var kompassi_static_image
          ports:
            - containerPort: 80
