apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kompassi
  annotations: !Var ingress_annotations
spec:
  tls: !Var ingress_tls
  rules:
    - host: !Var ingress_public_hostname
      http:
        paths:
          - path: /static
            backend:
              serviceName: nginx
              servicePort: 80
          - path: /media
            backend:
              serviceName: nginx
              servicePort: 80
          - path: /
            backend:
              serviceName: edegal
              servicePort: 8000
