ingress_public_hostnames:
  - kompassi.eu
  - conit.fi

postgres_managed: false
postgres_hostname: siilo.tracon.fi
postgres_database: kompassi
postgres_username: kompassi
postgres_ssl: true

redis_managed: false
redis_hostname: redis-ha-haproxy.redis-ha.svc.cluster.local
redis_broker_database: 9
redis_cache_database: 9

kompassi_secret_managed: false
kompassi_storage_pvc: false
kompassi_storage_pvc_storageclass: longhorn-nfs
kompassi_installation_name: Kompassi
kompassi_installation_slug: turska
kompassi_admins:
  - Santtu Pajukanta <santtu@pajukanta.fi>
kompassi_allowed_hosts: !Concat
  - !Var ingress_public_hostnames
  - [vara.kompassi.eu]
kompassi_cors_allowed_hosts:
  - infotv.ropecon.fi
  - v2.kompassi.eu

smtp_server: sr1.pahaip.fi
smtp_default_from_email: suunnistajat@kompassi.eu

setup_should_run: true

ingress_letsencrypt_enabled: true
ingress_letsencrypt_cluster_issuer: letsencrypt-prod

minio_bucket_name: kompassi
minio_endpoint_url: https://minio.con2.fi
