ingress_public_hostname: dev.kompassi.eu

postgres_managed: false
postgres_hostname: siilo.tracon.fi
postgres_database: kompassidev
postgres_username: kompassidev
postgres_ssl: true

redis_managed: false
redis_hostname: redis-ha-haproxy.redis-ha.svc.cluster.local
redis_broker_database: 7
redis_cache_database: 8

kompassi_repository: harbor.con2.fi/con2/kompassi
kompassi_tag: staging
kompassi_storage_pvc: true
kompassi_storage_pvc_storageclass: longhorn-nfs

setup_should_run: true

ingress_letsencrypt_enabled: true
ingress_letsencrypt_cluster_issuer: letsencrypt-prod
