ingress_public_hostname: dev.kompassi.eu

postgres_managed: false
postgres_hostname: siilo.tracon.fi
postgres_database: kompassidev

rabbitmq_image: rabbitmq:3.7.8
rabbitmq_vhost: kompassidev
rabbitmq_storage_pvc: false
rabbitmq_storage_cephfs: qbfs
rabbitmq_storage_cephfs_path: /kompassi-staging/rabbitmq-data

memcached_image: memcached:1.5.11-alpine

kompassi_tag: development-125
kompassi_storage_pvc: false
kompassi_storage_cephfs: qbfs
kompassi_storage_cephfs_path: /kompassi-staging/kompassi-media

# triggered by jenkins separately
setup_should_run: false

ingress_letsencrypt_enabled: true
ingress_letsencrypt_cluster_issuer: letsencrypt-prod
