apiVersion: apps/v1
kind: Deployment
metadata:
  name: kompassi
spec:
  selector:
    matchLabels:
      stack: kompassi
      component: kompassi
  template:
    metadata:
      labels:
        stack: kompassi
        component: kompassi
    spec:
      containers:
      - name: master
        image: !Var kompassi_image
        ports:
        - containerPort: 8000
        env: !Var environment
        readinessProbe:
          httpGet:
            path: /api/v1/status
            port: 8000
            httpHeaders:
              - name: Host
                value: !Var ingress_public_hostname
          initialDelaySeconds: 15
          periodSeconds: 30
        livenessProbe:
          httpGet:
            path: /api/v1/status
            port: 8000
            httpHeaders:
              - name: Host
                value: !Var ingress_public_hostname
          initialDelaySeconds: 30
          periodSeconds: 30
        volumeMounts:
          - !If
              test: !Any [!Var kompassi_storage_pvc, !Var kompassi_storage_cephfs]
              then:
                mountPath: /usr/src/app/media
                name: kompassi-media
      volumes:
        - !If
            test: !Var kompassi_storage_pvc
            then:
              name: kompassi-media
              persistentVolumeClaim:
                claimName: kompassi-media
        - !If
            test: !Var kompassi_storage_cephfs
            then: !Var kompassi_storage_cephfs_volume_definition
