apiVersion: v1
kind: Secret
metadata:
  name: kompassi
  labels:
    stack: kompassi
  annotations: !If
    test: !Var kompassi_secret_key
    then: !Void
    else:
      secret-generator.v1.mittwald.de/autogenerate: secretKey
type: Opaque
data:
  nexmoUsername: ''
  nexmoPassword: ''
  nexmoFrom: ''
  nexmoInboundKey: ''
  crowdApplicationName: ''
  crowdApplicationPassword: ''
  desuprofileOauth2ClientId: ''
  desuprofileOauth2ClientSecret: ''
  sshPrivateKey: 'Ym9ndXM='
  sshKnownHosts: 'Ym9ndXM='
  secretKey: !If
    test: !Var kompassi_secret_key
    then: !Base64,Var kompassi_secret_key
