apiVersion: v1
kind: Secret
metadata:
  name: kompassi
  labels:
    stack: kompassi
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: secretKey
type: Opaque
data:
  nexmoUsername: ''
  nexmoPassword: ''
  nexmoFrom: ''
  nexmoInboundKey: ''
  crowdApplicationName: ''
  crowdApplicationPassword: ''
  desuprofileOauth2ClientId: ''
  desuprofileOauth2ClientSecret: ''
