name: backend

on:
  push:
    paths:
      - backend/**
      - .github/workflows/backend.yaml
    branches:
      - main
  pull_request:
    paths:
      - backend/**
      - .github/workflows/backend.yaml
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      DOCKER_BUILDKIT: "1"
      COMPOSE_DOCKER_CLI_BUILD: "1"
    steps:
      - uses: actions/checkout@v1
      - uses: docker/setup-buildx-action@v3
      - run: |
          cd backend && docker compose -f docker-compose.test.yml up --exit-code-from test

  build:
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'push' }}
    env:
      SKAFFOLD_DEFAULT_REPO: ghcr.io/con2
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - id: cache-bin
        uses: actions/cache@v3
        with:
          path: bin
          key: ${{ runner.os }}-bin-2
      - if: steps.cache-bin.outputs.cache-hit != 'true'
        run: |
          mkdir bin
          curl -Lo bin/skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
          curl -Lo bin/kubectl https://dl.k8s.io/release/v1.22.0/bin/linux/amd64/kubectl
          chmod +x bin/skaffold bin/kubectl
      - run: echo "$PWD/bin" >> $GITHUB_PATH

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PASSWORD }}
      - uses: docker/setup-buildx-action@v3
      - id: build
        run: |
          cd backend
          python3 -m pip install -U pip setuptools wheel
          python3 -m pip install emskaffolden
          emskaffolden -E staging -- build --file-output build.json
      - uses: actions/upload-artifact@v2
        with:
          name: build-json
          path: backend/build.json

  # TODO DRY
  deploy_staging:
    runs-on: self-hosted
    needs: build
    environment: staging
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/download-artifact@v2
        with:
          name: build-json
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - id: cache-bin
        uses: actions/cache@v3
        with:
          path: bin
          key: ${{ runner.os }}-bin-2
      - if: steps.cache-bin.outputs.cache-hit != 'true'
        run: |
          mkdir bin
          curl -Lo bin/skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
          curl -Lo bin/kubectl https://dl.k8s.io/release/v1.22.0/bin/linux/amd64/kubectl
          chmod +x bin/skaffold bin/kubectl
      - run: echo "$PWD/bin" >> $GITHUB_PATH

      - run: |
          cd backend
          python3 -m pip install -U pip setuptools wheel
          python3 -m pip install emskaffolden
          emskaffolden -E staging -- deploy -n kompassi-staging -a build.json

  deploy_production:
    runs-on: self-hosted
    needs: build
    environment: production
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/download-artifact@v2
        with:
          name: build-json
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - id: cache-bin
        uses: actions/cache@v3
        with:
          path: bin
          key: ${{ runner.os }}-bin-2
      - if: steps.cache-bin.outputs.cache-hit != 'true'
        run: |
          mkdir bin
          curl -Lo bin/skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
          curl -Lo bin/kubectl https://dl.k8s.io/release/v1.22.0/bin/linux/amd64/kubectl
          chmod +x bin/skaffold bin/kubectl
      - run: echo "$PWD/bin" >> $GITHUB_PATH

      - run: |
          cd backend
          python3 -m pip install -U pip setuptools wheel
          python3 -m pip install emskaffolden
          emskaffolden -E production -- deploy -n kompassi-production -a build.json
